export const products = [
{
brend: "ARISTON",
name: 'Matis condens - Condensing Boiler',
price: "799,001",
description: '24 kW Methane - Indoor',
stars:4,
discount:"999,00",
},
{
brend: "ARISTON",
name: 'Phone Mini',
price: "699,00",
description: 'A great phone with one of the best cameras',
stars:4,
discount:0,
},
{
brend: "ARISTON",
name: 'Phone Standard',
price: "299,00",
description: 'A great phone with one of the best cameras',
stars:4,
discount:30,
},
{
brend: "ARISTON",
name: 'Phone Mini',
price: "699.00",
description: 'A great phone with one of the best cameras',
stars:4,
discount:30,
},
{
brend: "ARISTON",
name: 'Phone Standard',
price: "299,00",
description: 'A great phone with one of the best cameras',
stars:4,
discount:30,
},
{
brend: "ARISTON",
name: 'Phone Mini',
price: "699,00",
description: 'A great phone with one of the best cameras',
stars:4,
discount:30,
},
{
brend: "ARISTON",
name: 'Phone Standard',
price: "299,00",
description: 'A great phone with one of the best cameras',
stars:4,
discount:30,
},
];